### ISSUE TITLE
An image that fails to build doesn't stop the CI process

### ISSUE THREAD

**Issue by willtcarey** [brandnewbox/drydock_orb#10]
Meaning our half baked image continues to get pushed and then deployed to kubernetes 💀

Example: https://app.circleci.com/pipelines/github/brandnewbox/merchtable.com/599/workflows/d29615c3-ea80-407c-a61e-2b40917ff9f5/jobs/1590

**Comment by nathancolgate** [comment]
😬

**Comment by willtcarey** [comment]
I have tried triggering an error during the build process to see if I replicate this same "Build completed successfully" behavior out of S2I. I'm wondering if the particular error is the real culprit here. Maybe I need to replicate that specific error.

**Comment by nathancolgate** [comment]
@willtcarey i'm moving this to our next sprint. not 100% if it has been addressed already. if it has, please close this issue.

**Comment by willtcarey** [comment]
Hasn't been addressed. Please move it forward.

**Comment by willtcarey** [comment]
The status here is the fix is in the s2i scripts. The final step was rebuilding bnb-ruby images in order to get the new script loaded in. However I think what's happening more often than not is apps are just being upgraded from older Ruby versions to newer versions that have those fixes baked in. So I do not think we need a concerted effort to update apps here.
